
# SEO
title: Oğul Köseoğlu
description: Translator and interpreter based in Turkey, providing services in English and Turkish.

# Theme
remote_theme: 'internet-de-france/athena'
baseurl: '/ogulkoseoglu'

permalink: none

# Defaults

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      category_name: ""
  -
    scope:
      path: ""
      type: "posts"
    values:
      categories: ""
